service: twotoo-server

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  individually: true

functions:
  index:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
